name: "Test"
on: [push]
jobs:
  test:
    strategy:
      matrix:
        shellSource: [packages, flakes, file, devShell]
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Don't install `nix` ourselves to ensure that the action does.

      # Check that we've got the default Actions Runner path:
      - run: echo $PATH && rustc --version

      # Map to the right shell source:
      - uses: ./
        if: ${{ matrix.shellSource == "packages" }}
        with.packages: hello
        with.preserveDefaultPath: false
      - uses: ./
        if: ${{ matrix.shellSource == "flakes" }}
        with.flakes: nixpkgs#hello
        with.preserveDefaultPath: false
      - uses: ./
        if: ${{ matrix.shellSource == "file" }}
        with.file: test/shell.nix
        with.preserveDefaultPath: false
      - uses: ./
        if: ${{ matrix.shellSource == "devShell" }}
        with.devShell: test
        with.preserveDefaultPath: false

      # Test that the PATH has been cleared now:
      - run: |
          echo $PATH
          command -v rustc && exit 1 || :

      # Test that `hello` is on the path:
      - run: hello

      # `devShell` and `file` sources also exported the test case vars; check
      # that the vars roundtripped correctly in these shells:
      - if: ${{ matrix.shellSource == "devShell" }} || ${{ matrix.shellSource == "file" }}
        run: |
          source util.bash
          check_testcases

          # Check that modifications in `shellHook` take effect:
          echo $PATH | grep "foo" || exit 3

# Lint
# Test: env-vars on { flakes, devShell, packages, file } + run script
#  + test with `preserveDefaultPath` that checks that, like, rustc isn't on the path anymore
# matrix: { macOS, ubuntu }
